-- =====================================================================
-- MediShield - Production-safe seed data
-- =====================================================================
-- Normal application setup deliberately creates no users and contains no
-- deterministic credential. Create the first inactive administrator through:
--
--   php scripts\provision-initial-admin.php ...
--
-- Deterministic browser fixtures live only in scripts\seed-ui-test-users.php,
-- which refuses every database outside the explicit disposable UI allowlist.
-- =====================================================================
